-- Standard GitHub-hosted runner rates (USD per minute) as published by GitHub.
-- Source: https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions
-- Update rates via a follow-up migration (UPDATE …); do not edit this file once merged.
INSERT INTO "runner_pricing" ("runner_os", "runner_label", "per_minute_usd") VALUES
  ('ubuntu',      NULL, 0.008),
  ('windows',     NULL, 0.016),
  ('macos',       NULL, 0.080),
  ('self-hosted', NULL, 0.000);
